# Default values for polkadot-notification-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

notificationService:
  config: |
    {
        "accounts": [
            { "address" : "5HVz83t1pQRWPSQJTGsv2mNot9xFAnq6AU7ncBnwi2JHGWN3", "label": "rbwestend"},
            { "address" : "5EPGKcQ7yBQyH4cppqXR82FN8ktfmK6rx36c2N2aCJt2YpMe", "label": "rbwestmint"}
        ],
        "endpoints": [
            "wss://westend-rpc.polkadot.io",
            "wss://westmint-rpc.polkadot.io"
        ],
        "eventFilter-x": "all",
        "eventFilter": [
            "balances.Transfer",
            "system.CodeUpdated",
            "democracy.Passed"
        ],
        "matrix": {
               "userId": "rutger-monitor",
               "accessToken": "THIS VALUE IS OVERWRITTEN BY ENV MATRIX_TOKEN",
               "roomId": "!nLqvQVZPHeaKKJvEui:matrix.parity.io",
               "server": "https://matrix.parity.io"
        }
    }

replicaCount: 1

image:
  repository: rbazen/polkadot-notifications
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
